image:
  repository: abdulbhashiths/ipl-voter
  tag: "81cd20768a7c41225b9dc818ead19c048862a024"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 5000     
  nodePort: 30007      

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

persistence:
  enabled: true
  size: 100Mi
