image:
  repository: abdulbhashiths/ipl-voter
  tag: "dda573ee2de9333fd0b122608957b118918b3fd1"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 5000     
  nodePort: 30007      

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

persistence:
  enabled: true
  size: 100Mi
